version: '3.8'

services:
  app:
    image: my-books-app
    container_name: my-books-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=book_app
      - JWT_SECRET=supersecretkey
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my-books-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=book_app
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

# use this for ubuntu
# services:
#   db:
#     image: mysql:8.0
#     container_name: my-booksDB
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: my-secret-pw
#       MYSQL_DATABASE: book_app
#     volumes:
#       - mysql-data:/var/lib/mysql

#   app1:
#     build: .  # Build the Docker image from the current directory
#     container_name: my-books-app-1
#     ports:
#       - "3001:3000"  # Map host port 3001 to container port 3000
#     environment:
#       - DB_HOST=db
#       - DB_USER=root
#       - DB_PASSWORD=my-secret-pw
#       - DB_NAME=book_app
#     depends_on:
#       - db

#   app2:
#     build: .  # Build the Docker image from the current directory
#     container_name: my-books-app-2
#     ports:
#       - "3002:3000"  # Map host port 3002 to container port 3000
#     environment:
#       - DB_HOST=db
#       - DB_USER=root
#       - DB_PASSWORD=my-secret-pw
#       - DB_NAME=book_app
#     depends_on:
#       - db

# volumes:
#   mysql-data: